# Generated by Django 5.0.3 on 2024-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_title_category_name_rename_title_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('views_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
