# Generated by Django 5.0.3 on 2024-05-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_edit_category', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('can_change_published', 'Can change publishing')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
